### ISSUE TITLE
Create a REST API for agent interactions

### ISSUE THREAD

**Issue by chatGPTxx** [OpenDevin/OpenDevin#1075]
**What problem or use case are you trying to solve?**

Do you have plan to expose main features as API endpoints? So that we can easier integrate with other applications

**Describe the UX of the solution you'd like**

No UI

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by foragerr** [comment]
What would you deem "main features"
Would you mind describing what sort of integrations you're looking to build?

**Comment by rbren** [comment]
@chatGPTxx you can use OpenDevin as a python package currently, and you can use the webhook API describe here: https://github.com/OpenDevin/OpenDevin/tree/main/opendevin/server

A REST API would be nice (e.g. being able to start a task, then repeatedly call `POST /step` to advance the agent). But that would require persistent state (i.e. a database) rather than our current in-memory setup, so it's probably a ways off
