### ISSUE TITLE
genernate files on the openDevin root path  It was not agreed upon/ Under the workspaces directory

### ISSUE THREAD

**Issue by zhoumzh** [OpenDevin/OpenDevin#1109]
![image](https://github.com/OpenDevin/OpenDevin/assets/11206821/6f93fdfa-d4f3-4687-bfde-2ad3f201c3a7)

**Comment by rbren** [comment]
It looks like the issue is that OpenDevin mounted on the wrong directory here.

@zhoumzh we'll need more information to reproduce this. Please reopen a new issue and fill out the template, including your configuration and the current version

https://github.com/OpenDevin/OpenDevin/pull/1023 will probably fix this issue
