### ISSUE TITLE
Installing onnxruntime Failed

### ISSUE THREAD

**Issue by talentlo** [OpenDevin/OpenDevin#1117]
When I run the 'make build' command, I get the following error:

- Installing onnxruntime (1.17.3): Failed

  RuntimeError

  Unable to find installation candidates for onnxruntime (1.17.3)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install onnxruntime.

make[1]: *** [install-python-dependencies] 错误 1
make: *** [build] 错误 2

I used 'pip3 install onnxruntime' to successfully install onnxruntime, but it still doesn't work.

**Comment by rbren** [comment]
@talentlo can you try the docker installation method that was added a couple hours ago?

**Comment by rbren** [comment]
Going to close this now that we have docker

**Comment by xingyaoww** [comment]
I can actually produce this issue when starting from scratch to create a dev environment. It looks like this is required by `llamaindex`, and `pip install onnxruntime==1.17.3`. My guess is that this is due to `glibc` version of the system as point out here: https://github.com/run-llama/llama_index/issues/11448#issuecomment-1972594864
