### ISSUE TITLE
ERROR:root:<class 'ImportError'>: cannot import name 'DockerInteractive' from 'opendevin.sandbox.sandbox'  make: *** [Makefile:111: start-backend] Error 1

### ISSUE THREAD

**Issue by aichiyudemiaomiao** [OpenDevin/OpenDevin#1151]
config.tomal 
LLM_MODEL="ollama/llama2"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434/"
WORKSPACE_DIR="./workspace

make start-backend

![image](https://github.com/OpenDevin/OpenDevin/assets/33682312/ff2d12ac-65f6-4099-b7d7-84f6f7030336)

**Comment by SmartManoj** [comment]
Version?
Please fill the issue template

**Comment by foragerr** [comment]
`DockerInteractive` doesn't exist anymore. Please pull latest `main` if you're attempting to develop on OpenDevin.
if you run into additional difficulties, feel free to raise a new issue, using the [bug_report issue template](https://github.com/OpenDevin/OpenDevin/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). 

If you're looking to use it rather than develop for it, please see updated getting started instructions in README.
https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started
