### ISSUE TITLE
[Bug]: opendevin seems  donot do  Substantive work ， just  print out  "All done! What's next on the agenda?"

### ISSUE THREAD

**Issue by kinigsonstar** [OpenDevin/OpenDevin#1331]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

opendevin seems  donot do  Substantive work ， just  print out  "All done! What's next on the agenda?"

    
![1713947020645](https://github.com/OpenDevin/OpenDevin/assets/153916767/92074b8a-5f6a-4f09-822c-1433f9e53288)
![1713947126838](https://github.com/OpenDevin/OpenDevin/assets/153916767/72ebb00a-0cb0-44be-a215-a4bb02f8c7b4)
![1713947480880](https://github.com/OpenDevin/OpenDevin/assets/153916767/5deee52d-2e92-4157-9a54-9f47d1203acb)

### Current Version

```bash
INFO:     Started server process [7216]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Connection to localhost (127.0.0.1) 3000 port [tcp/*] succeeded!
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001 --host


  VITE v5.2.8  ready in 6945 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: http://172.16.2.230:3001/
  ➜  press h + enter to show help
```

### Installation and Configuration

```bash
make build; make run
```

### Model and Agent

LLM_MODEL="gpt-3.5-turbo"
LLM_API_KEY="sk-..."
LLM_EMBEDDING_MODEL=""
WORKSPACE_BASE="./workspace"
SANDBOX_TYPE="exec"

**Comment by enyst** [comment]
@kinigsonstar I modified your post to remove the API key. Please make sure to cancel it, if it was real, and make another.

On the issue: I've seen too that GPT-3.5 is sometimes doing that. You can restart the app, or at least the session, if necessary, it would get it back on track. I think the LLM decides to answer with 'finish' every time, and if that is so, there may or may not be a lot we can do, I'll look into it more.

**Comment by kinigsonstar** [comment]
thanks enyst,  the API key was not real,
Based on your preliminary analysis， the issue may be related to the LLM?

**Comment by enyst** [comment]
> the issue may be related to the LLM?

It can be, FWIW, GPT-4 is better, including on not "forgetting" what it was told, and on interpreting its task, and I believe I haven't seen this particular issue on GPT-4, but what you're seeing here is not just LLM.

For one, recently, we have changed the way it worked after finishing a task, so that it resets when it's done. I think you're on an older version. So if you upgrade, it might not repeat itself here, but: I think it will not be able to answer your question anyway, precisely because it "forgot" the previous task.

Also, currently the monologue agent works better if you give it a task to do. It's not so good as a chatbot. I think of it this way: it "thinks" it got a task from the user, so it tries to do what you say, not just answering questions, not just chatting.

That may change soon, and the behavior will be better, allowing for both another task, and some chat with the user about the previous task.

**Comment by rbren** [comment]
Which agent are you using? monologue?

**Comment by kinigsonstar** [comment]
thanks   enyst 
I will get latest version and  have a try with GPT-4

thanks rbren,
“Which agent are you using? monologue?”  I am new to opendevin ,  how can get which agent I used?

**Comment by rbren** [comment]
You can see it by clicking the settings wheel in the bottom right (or left, on older versions)

Monologue is default, so that's probably it

**Comment by li-boxuan** [comment]
I think there's a gap. From your screenshot, clearly you are hoping OpenDevin can understand & remember the context of previous task. I noticed you used wording like "this program", which OpenDevin has no idea about, because you gave OpenDevin a new task without telling it the context. It's very intuitive for one who is familiar with chatbots to have that mindset, but that doesn't perfectly suit here (today).

That being said, OpenDevin does have some "context" as in it keeps the current workspace, so it can read whatever files created by previous tasks. Could you please try rephrasing your task from

> how to run this program in linux

to

>  how to run 'hello_world.cpp' in linux

That might make a difference.

**Comment by rbren** [comment]
Going to close this one--I think it was fixed by a recent PR to reset task state properly
