### ISSUE TITLE
How is this different to other code builders? (fx. GPT Pilot; GPT Engineer; BabyAGI)

### ISSUE THREAD

**Issue by flexchar** [OpenDevin/OpenDevin#136]
Hey! 

I am actually really curious, how is this different to more known builders such as GPT Pilot or GPT Engineer or BabyAGI?

If all these frameworks build on the same thing - best available models than isn't hypothetically a waste of resources instead of focusing on those projects?

These are couple thoughts when I saw this repo in my TLDR newsletter. I am not affiliated with any products but I have tried aforementioned ones and they all share same issue of being a genius inside a gold fish brains. So my thought is that if efforts can be focused and getting one of existing projects going, perhaps that would contribute community as a whole more (referencing README). :)

Cheers!

**Comment by rbren** [comment]
Hey @flexchar, thanks for the question!

There are a lot of LLM-as-developer tools out there 😄 Others can chime in, but in my view, there are two key ways OpenDevin is different:
* OpenDevin is mainly an _interface_ for LLM developer agents. We have a UI, through which users can prompt the agent, observe its behavior, interrupt it, and give it hints
* That means we can support _many different agents_, built by different people. Currently we're keeping them in the `agenthub` directory, but I imagine we'll allow people to run agents from their own GitHub repos eventually.

So I see OpenDevin as more of a _platform_ for building developer agents, rather than just an agent itself. My hope is that we can take some of the tools you mentioned above and plug them into OpenDevin!

**Comment by flexchar** [comment]
Thank you for taking your time to share this, Robert. Excited to observe the journey!
