### ISSUE TITLE
[Bug]: OpenDevin dashboard freezes as soon as it is opened

### ISSUE THREAD

**Issue by Bartmr** [OpenDevin/OpenDevin#1563]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The OpenDevin dashboard crashes in Chrome right after opening it.

### Current Version

```bash
0.3.1 and 0.4.0
```

### Installation and Configuration

```bash
#!/bin/bash
set -euo pipefail

this_dir=$(dirname "$(realpath $0)")
cd "$this_dir"

workspace_base="/home/bartmr/Documents/repositories/org"

docker run \
    -e LLM_API_KEY=$OPENAI_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$workspace_base \
    -v $workspace_base:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.3.1 # and 0.4.0
```

### Model and Agent

- Model: OpenAI

### Reproduction Steps

1. Go to http://localhost:3000 after running devin

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/13721983/e1d2b53f-a0f7-4747-b44c-c84fe6dc9762)

**Comment by rbren** [comment]
@Bartmr thanks for the report! This is the first time I've seen this issue...

Are you able to see anything in the browse console?

**Comment by Bartmr** [comment]
After starting the container a second time, I got this. It's probably something weird Linux thing (my OS)

![image](https://github.com/OpenDevin/OpenDevin/assets/13721983/f97f6a8b-51e9-4d68-bd1f-9a0233e4a83a)

**Comment by SmartManoj** [comment]
FYI, you can run without frontend 
```bash
docker run \
    -e LLM_API_KEY=$OPENAI_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$workspace_base \
    -v $workspace_base:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.3.1 python opendevin/main.py  -d ./workspace -t "write bash script to print 5"```

**Comment by melihaltin** [comment]
I faced with this issue too . I cancelled the terminal and run 'make run' again. Then a window opened it was about permission for docker I allowed and it worked.

**Comment by yufansong** [comment]
> I faced with this issue too . I cancelled the terminal and run 'make run' again. Then a window opened it was about permission for docker I allowed and it worked.

@SmartManoj can you try this method. If it works, please close the issue. Thanks.

**Comment by SmartManoj** [comment]
I'm not the author.
@yufansong, Did you mean the OP @Bartmr?

**Comment by yufansong** [comment]
> @yufansong, I'm not the author. Did you mean the OP @Bartmr?

Oh sorry. Yeah, I mean @Bartmr

**Comment by Bartmr** [comment]
I ended up not using OpenDevin, as I just wanted a quick test. It ended up working with Chrome in incognito mode.

**Comment by neubig** [comment]
## Summary of Findings

I investigated whether workspace/runtime settings are exposed in the local GUI and whether the documentation properly covers running OpenHands without the Docker socket.

### 1. GUI Settings Exposure

**Workspace/runtime settings are NOT exposed in the GUI.** The frontend settings only include:
- LLM settings (model, API key, base URL)
- Agent settings
- Language preferences
- Git author settings
- MCP configuration
- Security/confirmation mode

The `RUNTIME` environment variable and related sandbox settings can only be configured via:
- Environment variables (e.g., `RUNTIME=local`, `SANDBOX_VOLUMES`)
- `config.toml` file

This is by design - these are advanced settings that are appropriately configured at the infrastructure level rather than through the GUI.

### 2. Documentation Updates

The documentation **was missing** clear instructions for running OpenHands in Docker without mounting the Docker socket. I have created a PR to address this:

**PR: https://github.com/OpenHands/docs/pull/227**

The documentation now covers two options for running without the Docker socket:

#### Option A: Process Runtime (`RUNTIME=local`)
```bash
docker run -it --rm --pull=always \
    -e RUNTIME=local \
    -e LOG_ALL_EVENTS=true \
    -v ~/.openhands:/.openhands \
    -v /path/to/your/workspace:/workspace \
    -p 3000:3000 \
    --name openhands-app \
    docker.openhands.dev/openhands/openhands:1.1
```
- No Docker socket required
- Agent executes directly inside the container
- ⚠️ No sandbox isolation

#### Option B: Remote Runtime (`RUNTIME=remote`)
```bash
docker run -it --rm --pull=always \
    -e RUNTIME=remote \
    -e SANDBOX_API_KEY=your-api-key \
    -e SANDBOX_REMOTE_RUNTIME_API_URL=https://your-runtime-api.com \
    -e LOG_ALL_EVENTS=true \
    -v ~/.openhands:/.openhands \
    -p 3000:3000 \
    --name openhands-app \
    docker.openhands.dev/openhands/openhands:1.1
```
- No Docker socket required
- Full sandbox isolation (sandboxes run in the cloud)
- Requires API access to a remote runtime service

### Documentation Pages Updated

1. **[Local Setup](/openhands/usage/run-openhands/local-setup)** - Added "Option 3: Using Docker Without Docker Socket" with both Process and Remote runtime options
2. **[Local Runtime](/openhands/usage/runtimes/local)** - Added section "Running Local Runtime Inside Docker" and updated prerequisites

These changes address the original issue by providing clear documentation for users who want to avoid mounting the Docker socket for security reasons.
