### ISSUE TITLE
Make Reconnecting to OpenDevin better when the Session crashes

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1778]
**What problem or use case are you trying to solve?**
Make Reconnecting to OpenDevin better when the Session crashes

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/5d2ec87d-629f-432a-ad25-3b19385b4da3)

STEP 27
11:46:42 - opendevin:INFO: codeact_agent.py:270 - Cost: 0.10 USD | Accumulated Cost: 1.88 USD
11:46:42 - ACTION
MessageAction(content='The tetris.js file has been updated to include functionality for the pause button. Please open the index.html file in your web browser again to see the updated functionality.\n\nYou should now see the restart, pause, and stop buttons below the Tetris game. The restart button will reset the game, the pause button will pause and resume the game, and the stop button will stop the game.\n\nIf you encounter any issues or have further requests, please let me know!', wait_for_response=True, action='message')
11:46:42 - opendevin:INFO: agent_controller.py:190 - Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.AWAITING_USER_INPUT
INFO:     ('172.17.0.1', 34652) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI1ZjA3ZDNmNy00NGYxLTQ5MWQtODVhMy0zNTczOTYxZTJkMTgifQ.Xj-_gxQTFH4jgAdQRKmRlCwCLvcbpbjnvNxkieTnDCs" [accepted]
Starting loop_recv for sid: 5f07d3f7-44f1-491d-85a3-3573961e2d18
11:46:42 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: 5f07d3f7-44f1-491d-85a3-3573961e2d18
INFO:     connection closed
INFO:     connection open
INFO:     172.17.0.1:34660 - "GET /api/messages/total HTTP/1.1" 200 OK

Connection lost randomly

now it's stuck like this

**Comment by AnAnalogGuy** [comment]
I have a similar (eventually the same) problem. It happens when i run into a session timeout. The session seems to be automatically resumed on the server side but upon triggering a resume from the frontend, the backend isn't able to restore the full context again (it seems the dialog is still there but the session is not restarted). 

@rbren Happy to help to track this down if needed - however i would need some guide on how/wehre to fetch the right logs/debug messages.

**Comment by SourikAdhikary** [comment]
@rbren happy to pick this up if it's fine

**Comment by rbren** [comment]
Would love any help on this one!

**Comment by AnAnalogGuy** [comment]
Just to add, a short observation:
- played around a bit over a couple of hours with opendevin today and it was stable (haven't changed anything, no reboot, nothing)
- I can't reproduce losing the session atm
- From what i did today, the main difference I see is yesterday the backend had to start some application processes which timedout (i.e. a http server). Maybe this somehow relates.

**Comment by 0xWick** [comment]
@AnAnalogGuy I also haven't faced a session timeout error. Although I have faced the Message Token Limit error using ChatGPT 3.5 turbo which also crashes the session and its impossible to get into that session after restarting although it has the chat history but the real context is somehow lost or not reloaded properpy.

You can try making it write large chunks of code with description to crash it and then see why the reload is not working properly.

**Comment by mamoodi** [comment]
@SourikAdhikary just wanted to check if you were planning on taking a look at this?

**Comment by SourikAdhikary** [comment]
> @SourikAdhikary just wanted to check if you were planning on taking a look at this?

Hi,
If anyone wants to pick this up kindly go ahead. I'm a bit occupied because of a medical emergency and won't be able to look at it properly before next week.

**Comment by AnAnalogGuy** [comment]
I didn't experience the same problem again since my last post (mentioning i didn't use OpenDevin a lot during that time since from my initial tests, it doesn't seem to be able to perform more complex tasks than what chatGPT is able to provide). 

However, just as an input, before digging into this, some documentation and if not available to directions from the project i would wait for, because it simply makes no sense to start reverse engineering the code to understand how session management and so on is done just for being able to start debugging). This is what i mentioned in my intial post: https://github.com/OpenDevin/OpenDevin/issues/1778#issuecomment-2134983796
