### ISSUE TITLE
[Bug]: Unit and Integration test check prevent PR from merging when changes are on ignored list

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#2011]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

PRs like this https://github.com/OpenDevin/OpenDevin/pull/1995 won't merge properly because all the edited files are in the ignored list, so the checks will NOT run integration/unit tests, BUT they are still waiting for "All test passed" (and it never passed which blocks the PR from merging).

https://github.com/OpenDevin/OpenDevin/blob/main/.github/workflows/run-integration-tests.yml

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/21c8a21a-73a3-4e49-aa01-5f1d1d5a1b08)

### Current Version

```bash
N/A
```

### Installation and Configuration

```bash
N/A
```

**Comment by li-boxuan** [comment]
The current CI setting has a bug:

If a test fails, this "All integration tests passed" check will skip, and then the PR can be merged! In fact, I had to create https://github.com/OpenDevin/OpenDevin/pull/2024 because a PR was merged even if the tests were failing.

<img width="867" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/25746010/46ee0493-6f03-44a6-9745-10cfcd729596">

Removing this "all tests passed" gate would solve this issue. I'll create a PR soon.
