### ISSUE TITLE
Support api_base for local model support

### ISSUE THREAD

**Issue by evolu8** [OpenDevin/OpenDevin#215]
**What problem or use case are you trying to solve?**

Can't run using local models

**Describe the UX of the solution you'd like**

No way to set api_base 

**Do you have thoughts on the technical implementation?**

Yep, add support for api_base here: https://github.com/OpenDevin/OpenDevin/blob/02a0367757b665171e9dff28fe434713382f2b92/opendevin/llm/llm.py#L5 

And in its subsequent partial construction

**Describe alternatives you've considered**

* Maybe not rely on ENVs? Would be nice to pass on initialise.
* Maybe also allow passing to LM Studio 2 (for multi model support, nice for agentic diversity)
**Additional context**
People will love you for making this. You are doing great thing here.

**Comment by rbren** [comment]
Hi @evolu8--you should be able to use any of the LiteLLM environment variables: https://litellm.vercel.app/docs/set_keys#environment-variables

Here's an existing issue to allow setting the model in `initiallize`, so that it can be set via UI: https://github.com/OpenDevin/OpenDevin/issues/209

I'll ask for supporting `api_base` as well

**Comment by rbren** [comment]
Closing in favor of #209
