### ISSUE TITLE
plan to switch to langchain agent?

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#2262]
## Describe your question

https://docs.google.com/document/d/1vrsreMuU80RmfC8kmJZTJ34mFnWnOjSx7QrXHCsFh3U/edit#heading=h.vp8ljjo2gjnu

shows langchain is the most popular agent framework.

any plan to include langchain tools/agents?

**Comment by neubig** [comment]
Thanks for the interest @josephykwang ! Actually the original agent for OpenDevin was based on LangChain, but we moved away from it because it wasn't necessary to implement the functionality that we needed. We definitely welcome contributions to our AgentHub that are based on langchain, but at the moment we don't have any plans to switch over unless a new agent based on langchain demonstrates superior performance to the ones that we already have. I'm going to close the issue, but we definitely welcome any contributions!
