### ISSUE TITLE
Feat: Improve Markdown in chat

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2367]
## What problem or use case are you trying to solve?

This is a followup issue to https://github.com/OpenDevin/OpenDevin/issues/1399

Markdown generation looks great (especially since the backticks got fixed), but could we tweak this:
* Detect if it is actual code then use a monospace font, otherwise a "regular" font
* Enable word-wrap for markdown in chat window
* Add a frontend option like `Use Markdown` that - if checked - will instruct with every prompt (to LLM) to structure the answer in markdown (if needed)
* Make the chat bubble itself completely markdown-enabled so that the LLM doesn't have to quote it as such (as in the screenshot)

This is what I just generated with current main branch for testing (some LUA code analysis):
![grafik](https://github.com/OpenDevin/OpenDevin/assets/10787084/90209200-677e-4d54-aa95-86c7437f8f02)

## More context

I'm seeing Gemini Pro by default using markdown in answers without being asked.

cc @amanape curious to hear your thoughts about this 🤗

**Comment by amanape** [comment]
> Detect if it is actual code then use a monospace font, otherwise a "regular" font

There is a `<SyntaxHighlighter>` component that handles styling code blocks:
https://github.com/OpenDevin/OpenDevin/blob/c6951eb6c1bbf1d03f8023470b053d5146f6a2f1/frontend/src/components/markdown/code.tsx#L23-L31

To address your other points:

Actually the chat bubbles are already able to render markdown with the `<Markdown>` component here:
https://github.com/OpenDevin/OpenDevin/blob/c6951eb6c1bbf1d03f8023470b053d5146f6a2f1/frontend/src/components/chat/ChatMessage.tsx#L19-L23

What happens in your screenshot is that LLM responds with markdown as a language ID for the syntax highlighter rather than actual markdown. The component then moves it into the classname and is handled by the `code` component

The raw text that the LLM in the screenshot generated is actually something like:
\`\`\`markdown
\# Title
\#\# Subtitle
\`\`\`

Where 'markdown' is the language ID that is moved to the classname to be handled by the custom `code` component.

Because of the backticks, they end up being wrapped in `<code>` elements, which remove any markdown styling provided by the `<Markdown>` component.

Trying to change the current logic to support rendering proper markdown in code blocks, may not be so straightforward due to how the `<Markdown>` and `<SyntaxHighligher>` components work under the hood, though I believe it is possible.

Another alternative I could think of is to update the prompt to specify the LLM not to wrap markdown text in a code block unless directly specified to do so.

---
Is this what you were adressing? Or have I misunderstood something 😅?

**Comment by tobitege** [comment]
Thanks so much for looking into this! 🏅 

I'll re-check if I can get the LLM to just answer in markdown syntax instead of "quoting" it in tags.
The class thing is not clear to me. Could we not just set a CSS style for that combo somehow?
I'm probably missing the point here. 😔

**Comment by amanape** [comment]
The `<Markdown>` and `<SyntaxHighlighter>` components are from a library as to not have to create the different syntax styles for different languages.

There _may_ be something in the documentation that point to some other alternative, but transforming markdown code blocks into actual markdown may also be undesired.

There may be scenarios in which the user wants to generate a markdown code block for other uses. That is why I suggested to prompt the LLM to avoid using markdown code-blocks _unless directly specified to do so._ At least in that case, depending on the users choice, they can have either format displayed to them rather always convert one to the other

**Comment by tobitege** [comment]
I'm still pondering using this issue as a testdrive for OpenDevin to solve. Keeping it open for a few more days. 😄
