### ISSUE TITLE
[Feature]: Prompt the user to rate the session after the agent stops

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#2419]
**What problem or use case are you trying to solve?**
Current feedback implementation does not necessarily take into account the sessions full life cycle

**Describe the UX of the solution you'd like**
Prompt the user directly to provide quick feedback after the end of session (e.g., when the agent stops)

**Do you have thoughts on the technical implementation?**
Display a toast-like notification with the positive/negative feedback actions after agent state is `'stopped'`

**Describe alternatives you've considered**
- Reuse the modal component to display the feedback options after the agent state is `'stopped'`
- Automatically send the session trajectory before the user closes/restarts OpenDevin

**Additional context**

**Comment by enyst** [comment]
Please let's not prompt the user in a way that is too intrusive. Maybe a small notice on bottom right of the page, that vanishes by itself in a few seconds if the user takes no action?

**Comment by tobitege** [comment]
After every "stopped" sounds a bit annoying.
Why not the other way around: do a reminder when a new session starts? 
For most of such things, I first always look for the setting to disable it. 😬

**Comment by tobitege** [comment]
I definitely understand that this issue is between a hard rock and a stone.
First, though, there needs to be some user opt-out or opt-in option for sending any data, like all the cookie confirmation prompts, but more decisive, especially with regard to e.g. EU privacy laws. I know that these exist but not all the details to them.
Just being on the "safe side" to avoid potential trouble from the get-go.

The desire to collect data I can understand, but personally I'd by default would not want it enabled unless being asked.
So that leads me to: whenever the UI pops up, check if the user has been previously asked and consented or not. Remember the user's choice and obey it.
Add an option to the Settings modal in case the user changes their mind.
If they voluntarily click the up-/down-buttons, then good, but do not take
that as a permanent consent statement.

Does that make sense?

**Comment by amanape** [comment]
@tobitege The implementation was never going to send data without the users knowledge. It would only be sent after the user explicitly does so.

You do make a point though.

CC @neubig
After some review, GDPR requires us to ask the user for consent to share data through a privacy notice. E.g.,
"We collect chat logs to improve our service. Your data will be anonymized and handled in accordance with our privacy policy. Do you agree to proceed? [Yes] [No]"

Something of the sorts must be displayed to the user when pressing either action button. Though we can display the same exact notice every time the user presses the button to submit feedback (if they previously declined).

It is absolutely required to do so if we are send personal data / PII with the feedback as well, which we do with their email and name (it may also be the case that the user shares certain PII during the chat, which could also fall under the same requirement)

To clarify: we must state the exact nature on how the data their sharing is being used (to train a model, update our service, etc...) to allow the user to decide whether they want to opt in or out, especially in cases where we receive their personal data as well.
