### ISSUE TITLE
[Experiment]: Measure effect of `truncate_observation` size on accuracy

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2540]
Currently `truncate_observation` defaults to 10,000 characters: https://github.com/OpenDevin/OpenDevin/blob/009f6f9ebc24b8cbce239f0929ac9c25bd3b055c/agenthub/codeact_agent/codeact_agent.py#L90

This might have an effect on accuracy/cost, and we should probably examine this in detail.

**Comment by tobitege** [comment]
It is characters, not tokens, since OD doesn't tokenize, or? 🤔

**Comment by neubig** [comment]
Right, characters, fixed. Which is even worse.

**Comment by xingyaoww** [comment]
Echoing discussion from https://opendevin.slack.com/archives/C078L0FUGUX/p1719450369932329?thread_ts=1718893390.852169&cid=C078L0FUGUX here:

`truncate_observation` truncate each single observation so that it is not too big. I remember i ran some early swe-bench experiments and decided the 99% (or 95%) percentile of the observation is around 10k, and set the truncation default to that (it shouldn't interfere too much with eval - but ofc it will be good to test!). In some cases, if we don't set the limit, some pip install log will gets too long that it will just blow off the context window directly...

EDIT: Check the swe-bench visualizer on HF space (https://huggingface.co/spaces/OpenDevin/evaluation?filepaths=outputs%2Fswe_bench_lite%2FCodeActAgent%2Fgpt-4o-2024-05-13_maxiter_30_N_v1.6-no-hint%2Foutput.jsonl) and open a random swe-bench experiment run. You can find the statistics of observation size: 10k is more like 90-95% percentile. Increasing it might bring some performance benefit, but we can't say for sure until we run the experiment.

**Comment by xingyaoww** [comment]
Echoing discussion from https://opendevin.slack.com/archives/C078L0FUGUX/p1719450369932329?thread_ts=1718893390.852169&cid=C078L0FUGUX here:

`truncate_observation` truncate each single observation so that it is not too big. I remember i ran some early swe-bench experiments and decided the 99% (or 95%) percentile of the observation is around 10k, and set the truncation default to that (it shouldn't interfere too much with eval - but ofc it will be good to test!). In some cases, if we don't set the limit, some pip install log will gets too long that it will just blow off the context window directly...

EDIT: Check the swe-bench visualizer on HF space (https://huggingface.co/spaces/OpenDevin/evaluation?filepaths=outputs%2Fswe_bench_lite%2FCodeActAgent%2Fgpt-4o-2024-05-13_maxiter_30_N_v1.6-no-hint%2Foutput.jsonl) and open a random swe-bench experiment run. You can find the statistics of observation size: 10k is more like 90-95% percentile. Increasing it might bring some performance benefit, but we can't say for sure until we run the experiment.

**Comment by xingyaoww** [comment]
Echoing discussion from https://opendevin.slack.com/archives/C078L0FUGUX/p1719450369932329?thread_ts=1718893390.852169&cid=C078L0FUGUX here:

`truncate_observation` truncate each single observation so that it is not too big. I remember i ran some early swe-bench experiments and decided the 99% (or 95%) percentile of the observation is around 10k, and set the truncation default to that (it shouldn't interfere too much with eval - but ofc it will be good to test!). In some cases, if we don't set the limit, some pip install log will gets too long that it will just blow off the context window directly...

EDIT: Check the swe-bench visualizer on HF space (https://huggingface.co/spaces/OpenDevin/evaluation?filepaths=outputs%2Fswe_bench_lite%2FCodeActAgent%2Fgpt-4o-2024-05-13_maxiter_30_N_v1.6-no-hint%2Foutput.jsonl) and open a random swe-bench experiment run. You can find the statistics of observation size: 10k is more like 90-95% percentile. Increasing it might bring some performance benefit, but we can't say for sure until we run the experiment.

**Comment by neubig** [comment]
I'm running this now, let's see the result.

**Comment by mamoodi** [comment]
@neubig just checking in on this issue since you last said you are running it.

**Comment by neubig** [comment]
I ran this but didn't see a clear positive trend... I'm not 100% confident in the results because I may have gotten some API errors effecting a few instances, but at least for now I think this can be closed.
