### ISSUE TITLE
[Feature Request] Indicate to user that the workspace set does not exist and that an empty workspace with that path is being created

### ISSUE THREAD

**Issue by MarArMar** [OpenDevin/OpenDevin#2839]
**What problem or use case are you trying to solve?**

This bug : https://github.com/OpenDevin/OpenDevin/issues/2837

**Describe the UX of the solution you'd like**

Something in the Readme to help me reset OpenDevin to a working state

**Do you have thoughts on the technical implementation?**

Yes this is a script I made but it did not work

```sh
#!/bin/bash

set -e

CONTAINERS=$(docker ps -aq --filter "name=opendevin")
VOLUMES=$(docker volume ls -q --filter "name=opendevin")

CONTAINERS_COUNT=$(echo "$CONTAINERS" | wc -w)
VOLUMES_COUNT=$(echo "$VOLUMES" | wc -w)

echo "Found $CONTAINERS_COUNT containers and $VOLUMES_COUNT volumes containing 'opendevin'"

if [ -n "$CONTAINERS" ]; then
  docker rm -f $CONTAINERS
  echo "Removed $CONTAINERS_COUNT containers"
fi

if docker image inspect ghcr.io/opendevin/opendevin:latest &>/dev/null; then
   echo "Image found, removing..."
   docker rmi ghcr.io/opendevin/opendevin:latest
 else
   echo "Image not found, skipping removal"
fi

docker builder prune -af

if [ -n "$VOLUMES" ]; then
  docker volume rm $VOLUMES
  echo "Removed $VOLUMES_COUNT volumes"
fi

echo "Done"
```

**Describe alternatives you've considered**

I guess build from source ?

**Additional context**

**Comment by mamoodi** [comment]
This is interesting.
I set my WORKSPACE_BASE to something nonexistent. Instead of OpenDevin erroring out or telling me there is no folder or some sort of warning before creating the folder, it just went ahead and created that folder.

I agree there should be some sort of message or warning of sorts that tells me the workspace I set doesn't really exist and that OpenDevin is creating an empty one. That way at least it's visible somewhere that this occurred. Let me update the issue title to reflect that.
