### ISSUE TITLE
Run OpenDevin on Openshift/K8S

### ISSUE THREAD

**Issue by eng-waleed1** [OpenDevin/OpenDevin#2887]
**Summary**
Run OpenDevin on Openshift/K8S. By default we can start with current root entrypoint.sh run but later we can think of running the whole application as non-root user.
**Motivation**
Getting wide range of integration in K8S/Openshift 
**Technical Design**
We can create PV, PVC, then a POD that run two containers "i.e. Both the app and sandbox containers" if needed. 
**Alternatives to Consider**
Run whole application as non-root user in order not to modify any security settings on OpenShift or K8S.
**Additional context**
I've tried to deploy it on my OpenShift lab and was able to run an agent with it.

**Comment by mamoodi** [comment]
Hi @eng-waleed1. Just to clarify are you asking that OpenDevin should just run permanently on OpenShift and people can access it without setting up locally?

If so, there is already plans to have a cloud hosted version as demo so people can test it out.

**Comment by eng-waleed1** [comment]
Hi @mamoodi , not that what I meant. I just wanted to get opendevin running on any openshift/k8s cluster. currently nothing mentioned about getting it running there or steps provided in case of someone needs to run it there. I hope this clarifies a little bit my point.

**Comment by mamoodi** [comment]
Ah yes I understand now. Essentially you want someone to document how to run OpenDevin on Openshift.
It will be hard to document every setup possible for OpenDevin that's why for now the only documentation is for running it locally.

We can leave this open but it's a specific use case and will require a good amount of time.

If you do happen to get it running, feel free to open a PR and add it instructions to somewhere in the documentation so others can use it if they want!

**Comment by eng-waleed1** [comment]
PR created. @mamoodi
