### ISSUE TITLE
Implement rate-limit backoff

### ISSUE THREAD

**Issue by bravekingzhang** [OpenDevin/OpenDevin#332]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**
should control the request
**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
<img width="939" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/4476322/4630e1cd-7fb0-479b-bc76-493678d740af">

**Comment by bravekingzhang** [comment]
<img width="686" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/4476322/511eb4d6-25d2-4253-b67d-d901a9057acd">

**Comment by rbren** [comment]
This might be an issue for LiteLLM--will investigate

**Comment by ishaan-jaff** [comment]
@bravekingzhang 
Use load balancing here: https://docs.litellm.ai/docs/proxy/load_balancing
or use fallbacks/retries: https://docs.litellm.ai/docs/proxy/reliability

**Comment by PatrickNercessian** [comment]
It also seems like we can use Router, which uses exponential backoff for rate limit errors

https://docs.litellm.ai/docs/routing#retries

However, I am skeptical that this works fully, after briefly testing the following changes to llm.py, it seems that it ends up in cooldown rather than retrying, at least for Claude Haiku. It almost seems that LiteLLM only checks for openai rate limit errors, but maybe I missed something.


![Screen Shot 2024-04-01 at 8 15 58 AM](https://github.com/OpenDevin/OpenDevin/assets/45547116/3da9e27e-4a90-43b0-b35f-baf814236be1)

**Comment by PatrickNercessian** [comment]
Discovered I needed to use allowed_fails to allow it to retry instead of going to cooldown queue. Creating pull request now
