### ISSUE TITLE
RuntimeError: uvloop does not support Windows at the moment

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#360]
Using source directory: 'C:\\Users\\pierr\\.virtualenvs\\OpenDevin-t35PKA65\\src'
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File
"C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in
_process\_in_process.py", line 353, in <module>
          main()
        File
"C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in
_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File
"C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in
_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File
"C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 325,
in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File
"C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 295,
in _get_build_requires
          self.run_setup()
        File
"C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 311,
in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:
[pipenv.exceptions.InstallError]:   × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [15 lines of output]
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[pipenv.exceptions.InstallError]:           main()
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Programs\Python\Python310\Lib\site-packages\pipenv\patched\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return hook(config_settings)
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return self._get_build_requires(config_settings, requirements=['wheel'])
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[pipenv.exceptions.InstallError]:           self.run_setup()
[pipenv.exceptions.InstallError]:         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-24a_jl7o\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[pipenv.exceptions.InstallError]:           exec(code, locals())
[pipenv.exceptions.InstallError]:         File "<string>", line 8, in <module>
[pipenv.exceptions.InstallError]:       RuntimeError: uvloop does not support Windows at the moment
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:
[pipenv.exceptions.InstallError]: × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]: │ exit code: 1
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]:
[pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Couldn't install package: {}
 Package installation failed...
C:\Users\pierr\AppData\Local\Programs\Python\Python310\lib\subprocess.py:1067: ResourceWarning: subprocess 41956 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=5 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=6 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by rbren** [comment]
Here's your issue:
> RuntimeError: uvloop does not support Windows at the moment

Are you running in WSL?

**Comment by PierrunoYT** [comment]
> Here's your issue:
> 
> > RuntimeError: uvloop does not support Windows at the moment
> 
> Are you running in WSL?

No because there is no WSL Guide so I had to use AI to Guide me through.

**Comment by rbren** [comment]
Seems like uvicorn won't run directly on Windows--you'll need WSL

**Comment by PierrunoYT** [comment]
> Seems like uvicorn won't run directly on Windows--you'll need WSL

Okay but I mean I needed to to ask AI to give me a guide how to install it everything which should be in the readme actually.

**Comment by rbren** [comment]
I just added WSL as a hard requirement to the readme, so that uvloop works

**Comment by Bongomannn** [comment]
I have the same issue. Iam also running on windows in normal mode without wsl. But iam wondering that there is no active code use of uvloop. It is only in Pipfile.lock. So I tried to delete the whole node in that file. -> Are you sure the project needs it? 

Then I had other problems with Makefile and i asked chatgpt to help me to translate to windows style. 

And now it works at least for 5minutes but its maybe not good enough to publish to all in repo. I have no clue what i have done. No idea what happens with that kind of file Pipfile.lock when i deleted there something and no idea about cmd or powershell but i have seen the results and they seems to be fine.  But not really repeatable.


- delete the node uvloop with all brackets out of Pipfile.lock 
- install docker desktop i have it done without use of wsl, setup of wsl was for me a pain
- install gnu make see the hardcoded path in makefile, had issue on installing to program files(X86) so C user was better
- install node.js
- pip install pypiwin32
- look in makefile below and switch the paths of makefile 
- I think the agents are using linux commands for the work on your windows filesystem so be carefull! for me worked a simple calculator python task but i dont know the rest of it maybe my concerns are not serious because of the use of docker

So here is my Makefile for Windows:
[Makefile.txt](https://github.com/OpenDevin/OpenDevin/files/14849571/Makefile.txt)

First results were fine but in the end there were errors:

Failed to stop container: 500 Server Error for http+docker://localnpipe/v1.44/co
ntainers/47b16445f5e6652f2c7bda6941d742defda5b2752c85c444e4eba11548cb620a/stop:
Internal Server Error ("cannot stop container: 47b16445f5e6652f2c7bda6941d742def
da5b2752c85c444e4eba11548cb620a: tried to kill container, but did not receive an
 exit event")
Error creating controller.
