### ISSUE TITLE
UI layout changes as you switch between tabs

### ISSUE THREAD

**Issue by penberg** [OpenDevin/OpenDevin#52]
**Describe the bug**

When you switch between tabs, the layout changes slightly, making the UI flicker.

**Steps to Reproduce**
1. `npm start`
2. Switch between planner and terminal tabs on Safari on macOS
3. You will see the UI flicker (see screenshots below)

**Additional context**

<img width="1439" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/81939/055e9520-a8d5-46f7-b006-f9af98872658">

<img width="1436" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/81939/0aab0ae7-47ae-487c-91ae-642aff79b8ef">

**Comment by Ghat0tkach** [comment]
@penberg , does by flicker you meant to say the irregular width increase of left pane with respect to terminal and planner?

thanks!

**Comment by yimothysu** [comment]
Can reproduce. This happens when the browser window width is 1341 pixels or smaller.

**Comment by yimothysu** [comment]
This happens on the line `terminal.open(terminalRef.current as HTMLDivElement)`. It seems loading the terminal into the DOM causes a layout shift.

**Comment by yimothysu** [comment]
After spending an hour wrestling with the layout, it turns out this is not a layout issue after all. This happens when the number of columns `cols` in the constructor of `XtermTerminal` is too large. Explicitly passing `0` resolves this bug because it is resized by the `fitAddon.fit()` thereafter.

The linked PR resolves this bug.
