### ISSUE TITLE
Token usage is very inefficient.

### ISSUE THREAD

**Issue by CakeCrusher** [OpenDevin/OpenDevin#539]
**Summary**
Used OpenDevin over the course of a day and it was prohibitively expensive (albeit I was using gpt4) I suspect prompting strategies like https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/monologue_agent/agent.py#L33 are the cause.
**Motivation**
This is very expensive to run.
**Alternatives to Consider**
Reduce dependence of prompting, refine the prompts.

**Comment by rbren** [comment]
Yeah, agents by their nature are expensive--they involve making prompts in a loop, and those prompts often need to carry quite a bit of info.

We have several open issues for different sorts of agents. But IMO precision/recall are far more top-of-mind than efficiency. Getting an agent to complete most tasks, even for $100/task, would be a huge leap forward.

Once we have agents that are usable, we can work on how to make them more efficient.

I'm going to close this one for now, because I don't think it's very actionable. But it's a good topic for discussion! I will bring it up in our internal #agents channel.
