### ISSUE TITLE
RuntimeError: Your system has an unsupported version of sqlite3.

### ISSUE THREAD

**Issue by mfzhsn** [OpenDevin/OpenDevin#571]
#### Describe the bug
Unable to run backend

#### Setup and configuration
**Current version**: Rocky 9.3 with Python 3.11 Running 

**
Whenever I try to run the backend, I get error with sqlite version

```
RuntimeError: Your system has an unsupported version of sqlite3. Chroma  requires sqlite3 >= 3.35.0.
Please visit  https://docs.trychroma.com/troubleshooting#sqlite to learn how  to upgrade. 
```

**My model and agent** (you can see these settings in the UI):
* Model: Default gpt-4
* Agent: 

**Commands I ran to install and run OpenDevin**:
```
make start-backend
```

**Steps to Reproduce**:
1. make start-backend

**Logs, error messages, and screenshots**:

**Comment by eredden** [comment]
Have you tried the steps listed in the referenced upgrade article [https://docs.trychroma.com/troubleshooting#sqlite](https://docs.trychroma.com/troubleshooting#sqlite) for your specific operating system? I would assume that carrying out those steps would help out with this issue. Give them a shot and let me know if they work out.


As a heads up, this issue is more likely to be rooted in the sqlite3 version on your system than it is to be an issue with OpenDevin. Not sure how the good folks here handle those sorts of issues but I'd be happy to help in the meantime.

**Comment by rbren** [comment]
Huh, I thought we solved this with the python 3.11 requirement. Thanks for the report

**Comment by djaym7** [comment]
openDevin/lib/python3.11/site-packages/chromadb/__init__.py", line 79, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
make[1]: *** [start-backend] Error 1
make[1]: Leaving directory `/local/home/Agent/OpenDevin'

(openDevin) ➜  OpenDevin git:(main) ✗ sqlite3 --version

3.46.0 2024-03-26 18:07:39 fe209099f5c348f1280b9b827ffbf6a6742ebdd1a23ef189445147894b1832ba (64-bit)

**Comment by djaym7** [comment]
python 3.12 has this dependency error installing [pipenv.exceptions.InstallError]: ERROR: No matching distribution found for onnxruntime==1.16.3

**Comment by djaym7** [comment]
<img width="1087" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/12378820/bbb59160-3271-453d-8051-012817b8d3c6">
This worked

**Comment by rbren** [comment]
Closing this now that we have poetry. Hopefully that helps--if you're still having trouble, feel free to open a new bug
