### ISSUE TITLE
Make Setup Config does not save defaults

### ISSUE THREAD

**Issue by androidworkz** [OpenDevin/OpenDevin#596]
#### Describe the bug
When running 'make setup-config', if you just hit enter (at least on windows), the default value is not saved in config.toml. When you start a project, the backend server faults saying that no model was passed.

#### Setup and configuration
**Current version**:
```bash
Newest version from this morning
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model: default
* Agent: default

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. Fresh install 
2. make setup-config

**Logs, error messages, and screenshots**:

#### Additional Context

I am on my phone right now

**Comment by Sinister-00** [comment]
Hi @androidworkz ,

I've submitted a pull request (#607) to address the issue you reported regarding the default value saving in the setup-config script. The changes made ensure that default values are correctly saved in the config.toml file even when users hit enter without providing input. This should resolve the problem you encountered where the backend server faulted due to missing model information.

Could you please review the changes in the pull request and verify if the issue has been resolved on your end?

Thank you!

**Comment by rbren** [comment]
This appears to be fixed now
