### ISSUE TITLE
More Setup Instructions required for Ubuntu 22.04, Windows 11, etc.

### ISSUE THREAD

**Issue by fournicknet** [OpenDevin/OpenDevin#686]
I have tried setting this up on Ubuntu 22.04 and Windows 11 and I am getting python run errors when trying to start the backend.  I have tried setting this project up from scratch twice and can't seem to get it to work.  I feel it is lacking instructions on how to set it up on ubuntu 22.04 or and Windows 11.

**Comment by stratte89** [comment]
> I have tried setting this up on Ubuntu 22.04 and Windows 11 and I am getting python run errors when trying to start the backend. I have tried setting this project up from scratch twice and can't seem to get it to work. I feel it is lacking instructions on how to set it up on ubuntu 22.04 or and Windows 11.

hey, i made a guide for ubuntu earlier
https://github.com/OpenDevin/OpenDevin/commit/08a2dfb01af1aec6743f5e4c23507d63980726c0#commitcomment-140559598

**Comment by neubig** [comment]
If you want to file a bug report, please follow the format in the bug template and provide the necessary information, this will help us resolve the issue. I'll close this issue for now due to lack of concrete information that we can act on, but we will be happy to take a look at a new issue with more details!
