### ISSUE TITLE
A error occurred while executing 'make build'.

### ISSUE THREAD

**Issue by silentbody** [OpenDevin/OpenDevin#760]
###When 'make build' reaches the command 'curl -sSL https://install.python-poetry.org/ | python3 -', the command cannot be executed and does not terminate, the reason is unknown.
```
lx@liuxin:/mnt/d/workspace/ai_project/OpenDevin$ sudo make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
Retrieving Poetry metadata
```

**Comment by JayQuimby** [comment]
> What's Next?
>   1. Sign in to your Docker account → docker login

I think you might need to sign into docker. I don't normally see this when I run make build...

```
:~/OpenDevin$ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing Python dependencies...
Requirement already satisfied: pipenv in /home/quimbo/miniconda3/lib/python3.11/site-packages (2023.12.1)
Requirement already satisfied: certifi in /home/quimbo/miniconda3/lib/python3.11/site-packages (from pipenv) (2024.2.2)
Requirement already satisfied: setuptools>=67 in /home/quimbo/miniconda3/lib/python3.11/site-packages (from pipenv) (68.2.2)
Requirement already satisfied: virtualenv>=20.24.2 in /home/quimbo/miniconda3/lib/python3.11/site-packages (from pipenv) (20.25.1)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/quimbo/miniconda3/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in /home/quimbo/miniconda3/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (3.13.3)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /home/quimbo/miniconda3/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (3.10.0)
Installing dependencies from Pipfile.lock (90ed62)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Setting up frontend environment...
Detect Node.js version...
Current Node.js version is 20.12.1, corepack is supported.
Lockfile is up to date, resolution step is skipped
Already up to date

> opendevin-frontend@0.1.0 prepare /home/quimbo/OpenDevin/frontend
> cd .. && husky install frontend/.husky

husky - Git hooks installed
Done in 1.3s
```

**Comment by silentbody** [comment]
It shouldn't be related to Docker, as 'docker pull' has already completed. It stops at this step 'Installing Python dependencies...'

**Comment by Xerizaf** [comment]
I think the problem is with curl command. I solved it by installing the latest version of curl with choco install curl. I'm now blocked at: "Building project..."
"Pulling Docker image..."
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
"Installing Python dependencies..."
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opendevin (0.1.0)
"Activating Poetry shell..."
"Installing pre-commit hooks..."
pre-commit installed at .git\hooks\pre-commit
"Setting up frontend environment..."
"Detect Node.js version..."
Current Node.js version is 21.7.2, corepack is supported.
-f non atteso.
make: *** [Makefile:27: build] Error 255

**Comment by heartsiddharth1** [comment]
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
make: poetry: No such file or directory
make: *** [Makefile:20: build] Error 127

**Comment by enyst** [comment]
Please see [this comment](https://github.com/OpenDevin/OpenDevin/issues/759#issuecomment-2039618274) and try setting the path.
