### ISSUE TITLE
error seed': 42

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#813]
Hi! I'm OpenDevin, an AI Software Engineer. What would you like to build with me today?
user avatar
bana mali danışmanlık firması için web sitesi tasarla ve çalıştır. Detaylı ve kapsamlı bir çalışma olsun.
assistant avatar
Starting new task...
assistant avatar
Oops. Something went wrong: gemini does not support parameters: {'seed': 42}. To drop these, set `litellm.drop_params=True` or for proxy: `litellm_settings: drop_params: true`
assistant avatar
Oops. Something went wrong: Expecting CmdRunAction or AgentEchoAction for Action

**Comment by neubig** [comment]
Thanks for the report.

This is probably a result of [this line](https://github.com/OpenDevin/OpenDevin/blob/0b5eea967f355842fc9529519c252e8a58771eba/agenthub/codeact_agent/codeact_agent.py#L127) being included in `codeact_agent`.

Maybe we can just remove the seed, since we don't use a seed in any of our other agents? WDYT @xingyaoww ?

**Comment by xingyaoww** [comment]
@neubig Sounds good! Submit #830 for this.
