### ISSUE TITLE
Implement new agent using AutoCodeRover's approach

### ISSUE THREAD

**Issue by foragerr** [OpenDevin/OpenDevin#942]
AutoCodeRover from NUS claims 22% on swe-bench-lite.
Their approach constructs an AST from a repo codebase to identify where in the code a patch needs to be applied.

Implement an agent based on ACR's approach.

https://arxiv.org/abs/2404.05427
https://github.com/nus-apr/auto-code-rover

**Comment by tot3v** [comment]
It now supports running on GitHub and local issues!

**Comment by neubig** [comment]
I don't think implementing autocoderover is high-priority given that we have better performance! https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/

**Comment by dsemba** [comment]
AutoCodeRover authors actually claim to resolve ~22% issues of SWE-bench lite. Why is the blog post https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/ saying AutoCodeRover achieves just 16%?

**Comment by neubig** [comment]
@dsemba see here: https://github.com/OpenDevin/OpenDevin/issues/1693#issuecomment-2105046751

**Comment by 0xdevalias** [comment]
> I don't think implementing autocoderover is high-priority given that we have better performance! [xwang.dev/blog/2024/opendevin-codeact-1.0-swebench](https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/)

@neubig I wouldn't necessarily claim that having a higher overall score means that OpenDevin couldn't benefit even more from techniques used in AutoCodeRover (or some other tool). IMO, to make that assessment you would need to be able to isolate/test how well their methods (eg. AST construction) compare against OpenDevin's equivalent methods. It may be that OpenDevin currently does better due to other parts.

--

In the space of AST parsing / better code 'repomaps', see also:

- #742

**Comment by 0xdevalias** [comment]
Also, looking at the repo, looks like AutoCodeRover is now much higher than OpenDevin on SWE-Bench lite (at least based on the 22% reported in the [linked blog post](https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/)):

- https://github.com/nus-apr/auto-code-rover
  - > [June 20, 2024] AutoCodeRover now achieves 30.67% efficacy (pass@1) on SWE-bench-lite!
- https://www.swebench.com/
  - It's currently sitting at number 3 on the leaderboard.
  - ![image](https://github.com/OpenDevin/OpenDevin/assets/753891/db52fed2-7bfa-4631-899b-e42f1c67c78f)
